# docker-compose.yml
version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: accessory_shop
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  fastapi:
    build: ./fastapi
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi:/app
    networks:
      - backend
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      - DATABASE_URL=mysql+pymysql://root:rootpass@mysql-db:3306/accessory_shop

  customer-service:
    build: ./customer-service
    ports:
      - "8003:8003"
    volumes:
      - ./customer-service:/app
    networks:
      - backend
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      - DATABASE_URL=mysql+pymysql://root:rootpass@mysql-db:3306/accessory_shop
      - PYTHONPATH=/app

  auth-service:
    build: ./auth-service
    ports:
      - "8002:8000"
    volumes:
      - ./auth-service:/app
    networks:
      - backend
    depends_on:
      mysql-db:
        condition: service_healthy
      customer-service:
        condition: service_started
    environment:
      - DATABASE_URL=mysql+pymysql://root:rootpass@mysql-db:3306/accessory_shop

  admin-service:
    build: ./admin-service
    ports:
      - "8001:8000"
    volumes:
      - ./admin-service:/app
    networks:
      - backend
    depends_on:
      mysql-db:
        condition: service_healthy
      fastapi:
        condition: service_started
    environment:
      - DATABASE_URL=mysql+pymysql://root:rootpass@mysql-db:3306/accessory_shop

  bff:
    build: ./bff
    command: ["npm", "start"]
    ports:
      - "4000:4000"
    volumes:
      - ./bff:/app
      - /app/node_modules
    networks:
      - backend
    depends_on:
      - fastapi
      - auth-service
      - customer-service
      - admin-service
    environment:
      - DATABASE_URL=mysql+pymysql://root:rootpass@mysql-db:3306/accessory_shop
      - AUTH_URL=http://auth-service:8000
      - CUSTOMER_URL=http://customer-service:8003

volumes:
  db-data:

networks:
  backend:
    driver: bridge
