version: "3.9"

services:
  fastapi:
    build: ./fastapi
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi:/app
    networks:
      - backend
    depends_on:
      - mysql-db
    environment:
      - DATABASE_URL=mysql+pymysql://root:rootpass@mysql-db:3306/accessory_shop

  bff:
    build: ./bff
    command: ["npm", "start"]
    ports:
      - "4000:4000"
    volumes:
      - ./bff:/app
    networks:
      - backend
    depends_on:
      - fastapi
    environment:
      - DATABASE_URL=mysql+pymysql://root:rootpass@mysql-db:3306/accessory_shop

  mysql-db:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: accessory_shop
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d
    networks:
      - backend


  auth-service:
    build: ./auth-service
    ports:
      - "8002:8000"
    volumes:
      - ./auth-service:/app
      - ./fastapi/models:/app/models
    networks:
      - backend
    depends_on:
      - mysql-db
    environment:
      - DATABASE_URL=mysql+pymysql://root:rootpass@mysql-db:3306/accessory_shop

  customer-service:
    build: ./customer-service
    ports:
      - "8003:8000"
    volumes:
      - ./customer-service:/app
    networks:
      - backend
    depends_on:
      - mysql-db
    environment:
      - DATABASE_URL=mysql+pymysql://root:rootpass@mysql-db:3306/accessory_shop

volumes:
  db-data:

networks:
  backend:
    driver: bridge
